/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Categoria,
  CategoriaNueva,
  CategoriaResumen,
  GrupoPreguntasRelacionadas,
} from '../models/index';
import {
    CategoriaFromJSON,
    CategoriaToJSON,
    CategoriaNuevaFromJSON,
    CategoriaNuevaToJSON,
    CategoriaResumenFromJSON,
    CategoriaResumenToJSON,
    GrupoPreguntasRelacionadasFromJSON,
    GrupoPreguntasRelacionadasToJSON,
} from '../models/index';

export interface CreateCategoriaRequest {
    categoriaNueva: CategoriaNueva;
}

export interface GetAllGruposPreguntasByCategoriaRequest {
    id: string;
}

export interface GetCategoriasResumenRequest {
    tipo?: string;
}

export interface GetOneCategoriaByIdRequest {
    id: string;
}

/**
 * 
 */
export class CategoriasApi extends runtime.BaseAPI {

    /**
     * Creates request options for createCategoria without sending the request
     */
    async createCategoriaRequestOpts(requestParameters: CreateCategoriaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['categoriaNueva'] == null) {
            throw new runtime.RequiredError(
                'categoriaNueva',
                'Required parameter "categoriaNueva" was null or undefined when calling createCategoria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/categoria`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CategoriaNuevaToJSON(requestParameters['categoriaNueva']),
        };
    }

    /**
     * Guardar una categoria
     */
    async createCategoriaRaw(requestParameters: CreateCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Categoria>> {
        const requestOptions = await this.createCategoriaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriaFromJSON(jsonValue));
    }

    /**
     * Guardar una categoria
     */
    async createCategoria(requestParameters: CreateCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Categoria> {
        const response = await this.createCategoriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllCategorias without sending the request
     */
    async getAllCategoriasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categoria`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener categorias
     */
    async getAllCategoriasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Categoria>>> {
        const requestOptions = await this.getAllCategoriasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoriaFromJSON));
    }

    /**
     * Obtener categorias
     */
    async getAllCategorias(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Categoria>> {
        const response = await this.getAllCategoriasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllGruposPreguntasByCategoria without sending the request
     */
    async getAllGruposPreguntasByCategoriaRequestOpts(requestParameters: GetAllGruposPreguntasByCategoriaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAllGruposPreguntasByCategoria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gruposDePreguntasRelacionadas/porCategoria/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas por Categoria
     */
    async getAllGruposPreguntasByCategoriaRaw(requestParameters: GetAllGruposPreguntasByCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GrupoPreguntasRelacionadas>>> {
        const requestOptions = await this.getAllGruposPreguntasByCategoriaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GrupoPreguntasRelacionadasFromJSON));
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas por Categoria
     */
    async getAllGruposPreguntasByCategoria(requestParameters: GetAllGruposPreguntasByCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GrupoPreguntasRelacionadas>> {
        const response = await this.getAllGruposPreguntasByCategoriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCategoriasResumen without sending the request
     */
    async getCategoriasResumenRequestOpts(requestParameters: GetCategoriasResumenRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['tipo'] != null) {
            queryParameters['tipo'] = requestParameters['tipo'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categoria/resumen`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener categorias con número de preguntas
     */
    async getCategoriasResumenRaw(requestParameters: GetCategoriasResumenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoriaResumen>>> {
        const requestOptions = await this.getCategoriasResumenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoriaResumenFromJSON));
    }

    /**
     * Obtener categorias con número de preguntas
     */
    async getCategoriasResumen(requestParameters: GetCategoriasResumenRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoriaResumen>> {
        const response = await this.getCategoriasResumenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOneCategoriaById without sending the request
     */
    async getOneCategoriaByIdRequestOpts(requestParameters: GetOneCategoriaByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOneCategoriaById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categoria/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener una categoria por id
     */
    async getOneCategoriaByIdRaw(requestParameters: GetOneCategoriaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Categoria>> {
        const requestOptions = await this.getOneCategoriaByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoriaFromJSON(jsonValue));
    }

    /**
     * Obtener una categoria por id
     */
    async getOneCategoriaById(requestParameters: GetOneCategoriaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Categoria> {
        const response = await this.getOneCategoriaByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
