/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Categoria,
} from '../models/index';
import {
    CategoriaFromJSON,
    CategoriaToJSON,
} from '../models/index';

/**
 * 
 */
export class CategoriasApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAllCategorias without sending the request
     */
    async getAllCategoriasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/categoria`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener categorias
     */
    async getAllCategoriasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Categoria>>> {
        const requestOptions = await this.getAllCategoriasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoriaFromJSON));
    }

    /**
     * Obtener categorias
     */
    async getAllCategorias(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Categoria>> {
        const response = await this.getAllCategoriasRaw(initOverrides);
        return await response.value();
    }

}
