/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Examen,
} from '../models/index';
import {
    ExamenFromJSON,
    ExamenToJSON,
} from '../models/index';

/**
 * 
 */
export class ExamenesApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAllExamenes without sending the request
     */
    async getAllExamenesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/examenes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener un listado de los Examenes
     */
    async getAllExamenesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Examen>>> {
        const requestOptions = await this.getAllExamenesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExamenFromJSON));
    }

    /**
     * Obtener un listado de los Examenes
     */
    async getAllExamenes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Examen>> {
        const response = await this.getAllExamenesRaw(initOverrides);
        return await response.value();
    }

}
