/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GrupoPreguntasRelacionadas,
} from '../models/index';
import {
    GrupoPreguntasRelacionadasFromJSON,
    GrupoPreguntasRelacionadasToJSON,
} from '../models/index';

export interface GetAllGruposPreguntasByCategoriaRequest {
    id: string;
}

/**
 * 
 */
export class GruposDePreguntasRelacionadasApi extends runtime.BaseAPI {

    /**
     * Creates request options for getAllGruposDePreguntasRelacionadas without sending the request
     */
    async getAllGruposDePreguntasRelacionadasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gruposDePreguntasRelacionadas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas
     */
    async getAllGruposDePreguntasRelacionadasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GrupoPreguntasRelacionadas>>> {
        const requestOptions = await this.getAllGruposDePreguntasRelacionadasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GrupoPreguntasRelacionadasFromJSON));
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas
     */
    async getAllGruposDePreguntasRelacionadas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GrupoPreguntasRelacionadas>> {
        const response = await this.getAllGruposDePreguntasRelacionadasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllGruposPreguntasByCategoria without sending the request
     */
    async getAllGruposPreguntasByCategoriaRequestOpts(requestParameters: GetAllGruposPreguntasByCategoriaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAllGruposPreguntasByCategoria().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gruposDePreguntasRelacionadas/porCategoria/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas por Categoria
     */
    async getAllGruposPreguntasByCategoriaRaw(requestParameters: GetAllGruposPreguntasByCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GrupoPreguntasRelacionadas>>> {
        const requestOptions = await this.getAllGruposPreguntasByCategoriaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GrupoPreguntasRelacionadasFromJSON));
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas por Categoria
     */
    async getAllGruposPreguntasByCategoria(requestParameters: GetAllGruposPreguntasByCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GrupoPreguntasRelacionadas>> {
        const response = await this.getAllGruposPreguntasByCategoriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
