/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoriaResumen,
  Practica,
  PracticaNueva,
} from '../models/index';
import {
    CategoriaResumenFromJSON,
    CategoriaResumenToJSON,
    PracticaFromJSON,
    PracticaToJSON,
    PracticaNuevaFromJSON,
    PracticaNuevaToJSON,
} from '../models/index';

export interface CreatePracticaRequest {
    practicaNueva: PracticaNueva;
}

export interface GetPracticaByIdRequest {
    id: string;
    page?: number;
    limit?: number;
    seed?: number;
}

export interface GetPracticaByIdInvertidaRequest {
    id: string;
    page?: number;
    limit?: number;
    seed?: number;
}

/**
 * 
 */
export class PracticasApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPractica without sending the request
     */
    async createPracticaRequestOpts(requestParameters: CreatePracticaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['practicaNueva'] == null) {
            throw new runtime.RequiredError(
                'practicaNueva',
                'Required parameter "practicaNueva" was null or undefined when calling createPractica().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/practica/crearPractica`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PracticaNuevaToJSON(requestParameters['practicaNueva']),
        };
    }

    /**
     * Guardar una practica
     */
    async createPracticaRaw(requestParameters: CreatePracticaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.createPracticaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Guardar una practica
     */
    async createPractica(requestParameters: CreatePracticaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.createPracticaRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllPracticas without sending the request
     */
    async getAllPracticasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/practica`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener todas las practicas con estadisticas
     */
    async getAllPracticasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoriaResumen>>> {
        const requestOptions = await this.getAllPracticasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoriaResumenFromJSON));
    }

    /**
     * Obtener todas las practicas con estadisticas
     */
    async getAllPracticas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoriaResumen>> {
        const response = await this.getAllPracticasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPracticaById without sending the request
     */
    async getPracticaByIdRequestOpts(requestParameters: GetPracticaByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPracticaById().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['seed'] != null) {
            queryParameters['seed'] = requestParameters['seed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/practica/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener una practica por id
     */
    async getPracticaByIdRaw(requestParameters: GetPracticaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Practica>> {
        const requestOptions = await this.getPracticaByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PracticaFromJSON(jsonValue));
    }

    /**
     * Obtener una practica por id
     */
    async getPracticaById(requestParameters: GetPracticaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Practica> {
        const response = await this.getPracticaByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPracticaByIdInvertida without sending the request
     */
    async getPracticaByIdInvertidaRequestOpts(requestParameters: GetPracticaByIdInvertidaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPracticaByIdInvertida().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['seed'] != null) {
            queryParameters['seed'] = requestParameters['seed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/practica/{id}/invertida`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener una practica por id cambiando preguntas por respuestas
     */
    async getPracticaByIdInvertidaRaw(requestParameters: GetPracticaByIdInvertidaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Practica>> {
        const requestOptions = await this.getPracticaByIdInvertidaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PracticaFromJSON(jsonValue));
    }

    /**
     * Obtener una practica por id cambiando preguntas por respuestas
     */
    async getPracticaByIdInvertida(requestParameters: GetPracticaByIdInvertidaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Practica> {
        const response = await this.getPracticaByIdInvertidaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for migracionPracticas without sending the request
     */
    async migracionPracticasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/practica/migracion`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Migra las preguntas a practicas
     */
    async migracionPracticasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.migracionPracticasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Migra las preguntas a practicas
     */
    async migracionPracticas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.migracionPracticasRaw(initOverrides);
    }

}
