/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Examen,
  GrupoPreguntasRelacionadas,
  Pregunta,
  RegistrarIntentoPreguntaRequest,
} from '../models/index';
import {
    ExamenFromJSON,
    ExamenToJSON,
    GrupoPreguntasRelacionadasFromJSON,
    GrupoPreguntasRelacionadasToJSON,
    PreguntaFromJSON,
    PreguntaToJSON,
    RegistrarIntentoPreguntaRequestFromJSON,
    RegistrarIntentoPreguntaRequestToJSON,
} from '../models/index';

export interface CreatePreguntaRequest {
    pregunta: Pregunta;
}

export interface DeletePreguntaByIdRequest {
    id: string;
}

export interface GetOnePreguntasByIdRequest {
    id: string;
}

export interface GetPreguntasPorCategoriaRequest {
    id: string;
    page?: number;
    limit?: number;
    seed?: number;
}

export interface RegistrarIntentoPreguntaOperationRequest {
    id: string;
    registrarIntentoPreguntaRequest: RegistrarIntentoPreguntaRequest;
}

export interface UpdatePreguntaByIdRequest {
    id: string;
    pregunta: Pregunta;
}

/**
 * 
 */
export class PreguntasApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPregunta without sending the request
     */
    async createPreguntaRequestOpts(requestParameters: CreatePreguntaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['pregunta'] == null) {
            throw new runtime.RequiredError(
                'pregunta',
                'Required parameter "pregunta" was null or undefined when calling createPregunta().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pregunta`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PreguntaToJSON(requestParameters['pregunta']),
        };
    }

    /**
     * Guardar una pregunta
     */
    async createPreguntaRaw(requestParameters: CreatePreguntaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Pregunta>>> {
        const requestOptions = await this.createPreguntaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PreguntaFromJSON));
    }

    /**
     * Guardar una pregunta
     */
    async createPregunta(requestParameters: CreatePreguntaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Pregunta>> {
        const response = await this.createPreguntaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePreguntaById without sending the request
     */
    async deletePreguntaByIdRequestOpts(requestParameters: DeletePreguntaByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePreguntaById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Eliminar una pregunta por id
     */
    async deletePreguntaByIdRaw(requestParameters: DeletePreguntaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePreguntaByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Eliminar una pregunta por id
     */
    async deletePreguntaById(requestParameters: DeletePreguntaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePreguntaByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getAllExamenes without sending the request
     */
    async getAllExamenesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/examenes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener un listado de los Examenes
     */
    async getAllExamenesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Examen>>> {
        const requestOptions = await this.getAllExamenesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ExamenFromJSON));
    }

    /**
     * Obtener un listado de los Examenes
     */
    async getAllExamenes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Examen>> {
        const response = await this.getAllExamenesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllGruposDePreguntasRelacionadas without sending the request
     */
    async getAllGruposDePreguntasRelacionadasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/gruposDePreguntasRelacionadas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas
     */
    async getAllGruposDePreguntasRelacionadasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<GrupoPreguntasRelacionadas>>> {
        const requestOptions = await this.getAllGruposDePreguntasRelacionadasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(GrupoPreguntasRelacionadasFromJSON));
    }

    /**
     * Obtener Grupos de Preguntas GrupoPreguntasRelacionadas
     */
    async getAllGruposDePreguntasRelacionadas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<GrupoPreguntasRelacionadas>> {
        const response = await this.getAllGruposDePreguntasRelacionadasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAllPreguntas without sending the request
     */
    async getAllPreguntasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener preguntas
     */
    async getAllPreguntasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Pregunta>>> {
        const requestOptions = await this.getAllPreguntasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PreguntaFromJSON));
    }

    /**
     * Obtener preguntas
     */
    async getAllPreguntas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Pregunta>> {
        const response = await this.getAllPreguntasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNumeroDePreguntas without sending the request
     */
    async getNumeroDePreguntasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta/getNumeroDePreguntas`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener el numero de preguntas actuales en la base de datos
     */
    async getNumeroDePreguntasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const requestOptions = await this.getNumeroDePreguntasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Obtener el numero de preguntas actuales en la base de datos
     */
    async getNumeroDePreguntas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.getNumeroDePreguntasRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getOnePreguntasById without sending the request
     */
    async getOnePreguntasByIdRequestOpts(requestParameters: GetOnePreguntasByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getOnePreguntasById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener una pregunta por id
     */
    async getOnePreguntasByIdRaw(requestParameters: GetOnePreguntasByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pregunta>> {
        const requestOptions = await this.getOnePreguntasByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreguntaFromJSON(jsonValue));
    }

    /**
     * Obtener una pregunta por id
     */
    async getOnePreguntasById(requestParameters: GetOnePreguntasByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pregunta> {
        const response = await this.getOnePreguntasByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getPreguntasPorCategoria without sending the request
     */
    async getPreguntasPorCategoriaRequestOpts(requestParameters: GetPreguntasPorCategoriaRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPreguntasPorCategoria().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['seed'] != null) {
            queryParameters['seed'] = requestParameters['seed'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta/porCategoria/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Obtener las preguntas que pertenecen a una categoria dada
     */
    async getPreguntasPorCategoriaRaw(requestParameters: GetPreguntasPorCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Pregunta>>> {
        const requestOptions = await this.getPreguntasPorCategoriaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PreguntaFromJSON));
    }

    /**
     * Obtener las preguntas que pertenecen a una categoria dada
     */
    async getPreguntasPorCategoria(requestParameters: GetPreguntasPorCategoriaRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Pregunta>> {
        const response = await this.getPreguntasPorCategoriaRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for registrarIntentoPregunta without sending the request
     */
    async registrarIntentoPreguntaRequestOpts(requestParameters: RegistrarIntentoPreguntaOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling registrarIntentoPregunta().'
            );
        }

        if (requestParameters['registrarIntentoPreguntaRequest'] == null) {
            throw new runtime.RequiredError(
                'registrarIntentoPreguntaRequest',
                'Required parameter "registrarIntentoPreguntaRequest" was null or undefined when calling registrarIntentoPregunta().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pregunta/{id}/intentos`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: RegistrarIntentoPreguntaRequestToJSON(requestParameters['registrarIntentoPreguntaRequest']),
        };
    }

    /**
     * Registrar intento de respuesta a una pregunta
     */
    async registrarIntentoPreguntaRaw(requestParameters: RegistrarIntentoPreguntaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.registrarIntentoPreguntaRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Registrar intento de respuesta a una pregunta
     */
    async registrarIntentoPregunta(requestParameters: RegistrarIntentoPreguntaOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.registrarIntentoPreguntaRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for reiniciarContadorDeEstadisticas without sending the request
     */
    async reiniciarContadorDeEstadisticasRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/pregunta/estadisticas/reiniciar`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reincia las estadisticas de las preguntas
     */
    async reiniciarContadorDeEstadisticasRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.reiniciarContadorDeEstadisticasRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reincia las estadisticas de las preguntas
     */
    async reiniciarContadorDeEstadisticas(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.reiniciarContadorDeEstadisticasRaw(initOverrides);
    }

    /**
     * Creates request options for updatePreguntaById without sending the request
     */
    async updatePreguntaByIdRequestOpts(requestParameters: UpdatePreguntaByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updatePreguntaById().'
            );
        }

        if (requestParameters['pregunta'] == null) {
            throw new runtime.RequiredError(
                'pregunta',
                'Required parameter "pregunta" was null or undefined when calling updatePreguntaById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/pregunta/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PreguntaToJSON(requestParameters['pregunta']),
        };
    }

    /**
     * Actualizar una pregunta por id
     */
    async updatePreguntaByIdRaw(requestParameters: UpdatePreguntaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Pregunta>> {
        const requestOptions = await this.updatePreguntaByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PreguntaFromJSON(jsonValue));
    }

    /**
     * Actualizar una pregunta por id
     */
    async updatePreguntaById(requestParameters: UpdatePreguntaByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Pregunta> {
        const response = await this.updatePreguntaByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
