/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Estadistica } from './Estadistica';
import {
    EstadisticaFromJSON,
    EstadisticaFromJSONTyped,
    EstadisticaToJSON,
    EstadisticaToJSONTyped,
} from './Estadistica';

/**
 * 
 * @export
 * @interface CategoriaResumen
 */
export interface CategoriaResumen {
    /**
     * 
     * @type {string}
     * @memberof CategoriaResumen
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CategoriaResumen
     */
    nombre: string;
    /**
     * 
     * @type {number}
     * @memberof CategoriaResumen
     */
    numeroPreguntas: number;
    /**
     * 
     * @type {Estadistica}
     * @memberof CategoriaResumen
     */
    estadisticas: Estadistica;
}

/**
 * Check if a given object implements the CategoriaResumen interface.
 */
export function instanceOfCategoriaResumen(value: object): value is CategoriaResumen {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    if (!('numeroPreguntas' in value) || value['numeroPreguntas'] === undefined) return false;
    if (!('estadisticas' in value) || value['estadisticas'] === undefined) return false;
    return true;
}

export function CategoriaResumenFromJSON(json: any): CategoriaResumen {
    return CategoriaResumenFromJSONTyped(json, false);
}

export function CategoriaResumenFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriaResumen {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
        'numeroPreguntas': json['numeroPreguntas'],
        'estadisticas': EstadisticaFromJSON(json['estadisticas']),
    };
}

export function CategoriaResumenToJSON(json: any): CategoriaResumen {
    return CategoriaResumenToJSONTyped(json, false);
}

export function CategoriaResumenToJSONTyped(value?: CategoriaResumen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'numeroPreguntas': value['numeroPreguntas'],
        'estadisticas': EstadisticaToJSON(value['estadisticas']),
    };
}

