/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CategoriaNueva
 */
export interface CategoriaNueva {
    /**
     * 
     * @type {string}
     * @memberof CategoriaNueva
     */
    nombre: string;
}

/**
 * Check if a given object implements the CategoriaNueva interface.
 */
export function instanceOfCategoriaNueva(value: object): value is CategoriaNueva {
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    return true;
}

export function CategoriaNuevaFromJSON(json: any): CategoriaNueva {
    return CategoriaNuevaFromJSONTyped(json, false);
}

export function CategoriaNuevaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoriaNueva {
    if (json == null) {
        return json;
    }
    return {
        
        'nombre': json['nombre'],
    };
}

export function CategoriaNuevaToJSON(json: any): CategoriaNueva {
    return CategoriaNuevaToJSONTyped(json, false);
}

export function CategoriaNuevaToJSONTyped(value?: CategoriaNueva | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nombre': value['nombre'],
    };
}

