/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Categoria
 */
export interface Categoria {
    /**
     * 
     * @type {string}
     * @memberof Categoria
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Categoria
     */
    nombre: string;
}

/**
 * Check if a given object implements the Categoria interface.
 */
export function instanceOfCategoria(value: object): value is Categoria {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    return true;
}

export function CategoriaFromJSON(json: any): Categoria {
    return CategoriaFromJSONTyped(json, false);
}

export function CategoriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Categoria {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
    };
}

export function CategoriaToJSON(json: any): Categoria {
    return CategoriaToJSONTyped(json, false);
}

export function CategoriaToJSONTyped(value?: Categoria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
    };
}

