/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Estadistica
 */
export interface Estadistica {
    /**
     * 
     * @type {number}
     * @memberof Estadistica
     */
    aciertos: number;
    /**
     * 
     * @type {number}
     * @memberof Estadistica
     */
    fallos: number;
    /**
     * 
     * @type {number}
     * @memberof Estadistica
     */
    total: number;
}

/**
 * Check if a given object implements the Estadistica interface.
 */
export function instanceOfEstadistica(value: object): value is Estadistica {
    if (!('aciertos' in value) || value['aciertos'] === undefined) return false;
    if (!('fallos' in value) || value['fallos'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function EstadisticaFromJSON(json: any): Estadistica {
    return EstadisticaFromJSONTyped(json, false);
}

export function EstadisticaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Estadistica {
    if (json == null) {
        return json;
    }
    return {
        
        'aciertos': json['aciertos'],
        'fallos': json['fallos'],
        'total': json['total'],
    };
}

export function EstadisticaToJSON(json: any): Estadistica {
    return EstadisticaToJSONTyped(json, false);
}

export function EstadisticaToJSONTyped(value?: Estadistica | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'aciertos': value['aciertos'],
        'fallos': value['fallos'],
        'total': value['total'],
    };
}

