/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const Estado = {
    Gpt: 'GPT',
    Verificado: 'VERIFICADO',
    Revisado: 'REVISADO',
    Enterrado: 'ENTERRADO',
    Desenterrado: 'DESENTERRADO',
    Marcado: 'MARCADO'
} as const;
export type Estado = typeof Estado[keyof typeof Estado];


export function instanceOfEstado(value: any): boolean {
    for (const key in Estado) {
        if (Object.prototype.hasOwnProperty.call(Estado, key)) {
            if (Estado[key as keyof typeof Estado] === value) {
                return true;
            }
        }
    }
    return false;
}

export function EstadoFromJSON(json: any): Estado {
    return EstadoFromJSONTyped(json, false);
}

export function EstadoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Estado {
    return json as Estado;
}

export function EstadoToJSON(value?: Estado | null): any {
    return value as any;
}

export function EstadoToJSONTyped(value: any, ignoreDiscriminator: boolean): Estado {
    return value as Estado;
}

