/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExamenPreguntasInner } from './ExamenPreguntasInner';
import {
    ExamenPreguntasInnerFromJSON,
    ExamenPreguntasInnerFromJSONTyped,
    ExamenPreguntasInnerToJSON,
    ExamenPreguntasInnerToJSONTyped,
} from './ExamenPreguntasInner';

/**
 * 
 * @export
 * @interface Examen
 */
export interface Examen {
    /**
     * 
     * @type {string}
     * @memberof Examen
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Examen
     */
    nombre: string;
    /**
     * 
     * @type {number}
     * @memberof Examen
     */
    anio?: number;
    /**
     * 
     * @type {string}
     * @memberof Examen
     */
    grupo?: string;
    /**
     * 
     * @type {string}
     * @memberof Examen
     */
    subgrupo?: string;
    /**
     * 
     * @type {Array<ExamenPreguntasInner>}
     * @memberof Examen
     */
    preguntas?: Array<ExamenPreguntasInner>;
}

/**
 * Check if a given object implements the Examen interface.
 */
export function instanceOfExamen(value: object): value is Examen {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('nombre' in value) || value['nombre'] === undefined) return false;
    return true;
}

export function ExamenFromJSON(json: any): Examen {
    return ExamenFromJSONTyped(json, false);
}

export function ExamenFromJSONTyped(json: any, ignoreDiscriminator: boolean): Examen {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'nombre': json['nombre'],
        'anio': json['anio'] == null ? undefined : json['anio'],
        'grupo': json['grupo'] == null ? undefined : json['grupo'],
        'subgrupo': json['subgrupo'] == null ? undefined : json['subgrupo'],
        'preguntas': json['preguntas'] == null ? undefined : ((json['preguntas'] as Array<any>).map(ExamenPreguntasInnerFromJSON)),
    };
}

export function ExamenToJSON(json: any): Examen {
    return ExamenToJSONTyped(json, false);
}

export function ExamenToJSONTyped(value?: Examen | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nombre': value['nombre'],
        'anio': value['anio'],
        'grupo': value['grupo'],
        'subgrupo': value['subgrupo'],
        'preguntas': value['preguntas'] == null ? undefined : ((value['preguntas'] as Array<any>).map(ExamenPreguntasInnerToJSON)),
    };
}

