/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GrupoPreguntasRelacionadas } from './GrupoPreguntasRelacionadas';
import {
    instanceOfGrupoPreguntasRelacionadas,
    GrupoPreguntasRelacionadasFromJSON,
    GrupoPreguntasRelacionadasFromJSONTyped,
    GrupoPreguntasRelacionadasToJSON,
} from './GrupoPreguntasRelacionadas';
import type { Pregunta } from './Pregunta';
import {
    instanceOfPregunta,
    PreguntaFromJSON,
    PreguntaFromJSONTyped,
    PreguntaToJSON,
} from './Pregunta';

/**
 * @type ExamenPreguntasInner
 * 
 * @export
 */
export type ExamenPreguntasInner = GrupoPreguntasRelacionadas | Pregunta;

export function ExamenPreguntasInnerFromJSON(json: any): ExamenPreguntasInner {
    return ExamenPreguntasInnerFromJSONTyped(json, false);
}

export function ExamenPreguntasInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExamenPreguntasInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfGrupoPreguntasRelacionadas(json)) {
        return GrupoPreguntasRelacionadasFromJSONTyped(json, true);
    }
    if (instanceOfPregunta(json)) {
        return PreguntaFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ExamenPreguntasInnerToJSON(json: any): any {
    return ExamenPreguntasInnerToJSONTyped(json, false);
}

export function ExamenPreguntasInnerToJSONTyped(value?: ExamenPreguntasInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfGrupoPreguntasRelacionadas(value)) {
        return GrupoPreguntasRelacionadasToJSON(value as GrupoPreguntasRelacionadas);
    }
    if (instanceOfPregunta(value)) {
        return PreguntaToJSON(value as Pregunta);
    }
    return {};
}

