/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pregunta } from './Pregunta';
import {
    PreguntaFromJSON,
    PreguntaFromJSONTyped,
    PreguntaToJSON,
    PreguntaToJSONTyped,
} from './Pregunta';

/**
 * 
 * @export
 * @interface GrupoPreguntasRelacionadas
 */
export interface GrupoPreguntasRelacionadas {
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    idGrupoPregunta: string;
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    textoPre: string;
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    textoPos?: string;
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    codigo: string;
    /**
     * 
     * @type {string}
     * @memberof GrupoPreguntasRelacionadas
     */
    lenguaje: string;
    /**
     * 
     * @type {Array<Pregunta>}
     * @memberof GrupoPreguntasRelacionadas
     */
    preguntas: Array<Pregunta>;
}

/**
 * Check if a given object implements the GrupoPreguntasRelacionadas interface.
 */
export function instanceOfGrupoPreguntasRelacionadas(value: object): value is GrupoPreguntasRelacionadas {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('idGrupoPregunta' in value) || value['idGrupoPregunta'] === undefined) return false;
    if (!('textoPre' in value) || value['textoPre'] === undefined) return false;
    if (!('codigo' in value) || value['codigo'] === undefined) return false;
    if (!('lenguaje' in value) || value['lenguaje'] === undefined) return false;
    if (!('preguntas' in value) || value['preguntas'] === undefined) return false;
    return true;
}

export function GrupoPreguntasRelacionadasFromJSON(json: any): GrupoPreguntasRelacionadas {
    return GrupoPreguntasRelacionadasFromJSONTyped(json, false);
}

export function GrupoPreguntasRelacionadasFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrupoPreguntasRelacionadas {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'idGrupoPregunta': json['idGrupoPregunta'],
        'textoPre': json['textoPre'],
        'textoPos': json['textoPos'] == null ? undefined : json['textoPos'],
        'codigo': json['codigo'],
        'lenguaje': json['lenguaje'],
        'preguntas': ((json['preguntas'] as Array<any>).map(PreguntaFromJSON)),
    };
}

export function GrupoPreguntasRelacionadasToJSON(json: any): GrupoPreguntasRelacionadas {
    return GrupoPreguntasRelacionadasToJSONTyped(json, false);
}

export function GrupoPreguntasRelacionadasToJSONTyped(value?: GrupoPreguntasRelacionadas | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'idGrupoPregunta': value['idGrupoPregunta'],
        'textoPre': value['textoPre'],
        'textoPos': value['textoPos'],
        'codigo': value['codigo'],
        'lenguaje': value['lenguaje'],
        'preguntas': ((value['preguntas'] as Array<any>).map(PreguntaToJSON)),
    };
}

