/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pregunta } from './Pregunta';
import {
    PreguntaFromJSON,
    PreguntaFromJSONTyped,
    PreguntaToJSON,
    PreguntaToJSONTyped,
} from './Pregunta';

/**
 * 
 * @export
 * @interface ListaDePreguntasPorCategoria
 */
export interface ListaDePreguntasPorCategoria {
    /**
     * 
     * @type {string}
     * @memberof ListaDePreguntasPorCategoria
     */
    idCategoriaPrincipal: string;
    /**
     * 
     * @type {string}
     * @memberof ListaDePreguntasPorCategoria
     */
    nombreCategoriaPrincipal: string;
    /**
     * 
     * @type {Array<Pregunta>}
     * @memberof ListaDePreguntasPorCategoria
     */
    preguntas: Array<Pregunta>;
}

/**
 * Check if a given object implements the ListaDePreguntasPorCategoria interface.
 */
export function instanceOfListaDePreguntasPorCategoria(value: object): value is ListaDePreguntasPorCategoria {
    if (!('idCategoriaPrincipal' in value) || value['idCategoriaPrincipal'] === undefined) return false;
    if (!('nombreCategoriaPrincipal' in value) || value['nombreCategoriaPrincipal'] === undefined) return false;
    if (!('preguntas' in value) || value['preguntas'] === undefined) return false;
    return true;
}

export function ListaDePreguntasPorCategoriaFromJSON(json: any): ListaDePreguntasPorCategoria {
    return ListaDePreguntasPorCategoriaFromJSONTyped(json, false);
}

export function ListaDePreguntasPorCategoriaFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListaDePreguntasPorCategoria {
    if (json == null) {
        return json;
    }
    return {
        
        'idCategoriaPrincipal': json['idCategoriaPrincipal'],
        'nombreCategoriaPrincipal': json['nombreCategoriaPrincipal'],
        'preguntas': ((json['preguntas'] as Array<any>).map(PreguntaFromJSON)),
    };
}

export function ListaDePreguntasPorCategoriaToJSON(json: any): ListaDePreguntasPorCategoria {
    return ListaDePreguntasPorCategoriaToJSONTyped(json, false);
}

export function ListaDePreguntasPorCategoriaToJSONTyped(value?: ListaDePreguntasPorCategoria | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idCategoriaPrincipal': value['idCategoriaPrincipal'],
        'nombreCategoriaPrincipal': value['nombreCategoriaPrincipal'],
        'preguntas': ((value['preguntas'] as Array<any>).map(PreguntaToJSON)),
    };
}

