/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Pregunta } from './Pregunta';
import {
    PreguntaFromJSON,
    PreguntaFromJSONTyped,
    PreguntaToJSON,
    PreguntaToJSONTyped,
} from './Pregunta';

/**
 * 
 * @export
 * @interface Practica
 */
export interface Practica {
    /**
     * 
     * @type {string}
     * @memberof Practica
     */
    idPractica: string;
    /**
     * 
     * @type {string}
     * @memberof Practica
     */
    nombrePractica: string;
    /**
     * 
     * @type {Array<Pregunta>}
     * @memberof Practica
     */
    preguntas: Array<Pregunta>;
}

/**
 * Check if a given object implements the Practica interface.
 */
export function instanceOfPractica(value: object): value is Practica {
    if (!('idPractica' in value) || value['idPractica'] === undefined) return false;
    if (!('nombrePractica' in value) || value['nombrePractica'] === undefined) return false;
    if (!('preguntas' in value) || value['preguntas'] === undefined) return false;
    return true;
}

export function PracticaFromJSON(json: any): Practica {
    return PracticaFromJSONTyped(json, false);
}

export function PracticaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Practica {
    if (json == null) {
        return json;
    }
    return {
        
        'idPractica': json['idPractica'],
        'nombrePractica': json['nombrePractica'],
        'preguntas': ((json['preguntas'] as Array<any>).map(PreguntaFromJSON)),
    };
}

export function PracticaToJSON(json: any): Practica {
    return PracticaToJSONTyped(json, false);
}

export function PracticaToJSONTyped(value?: Practica | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idPractica': value['idPractica'],
        'nombrePractica': value['nombrePractica'],
        'preguntas': ((value['preguntas'] as Array<any>).map(PreguntaToJSON)),
    };
}

