/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Categoria } from './Categoria';
import {
    CategoriaFromJSON,
    CategoriaFromJSONTyped,
    CategoriaToJSON,
    CategoriaToJSONTyped,
} from './Categoria';
import type { Respuesta } from './Respuesta';
import {
    RespuestaFromJSON,
    RespuestaFromJSONTyped,
    RespuestaToJSON,
    RespuestaToJSONTyped,
} from './Respuesta';

/**
 * 
 * @export
 * @interface PreguntaNueva
 */
export interface PreguntaNueva {
    /**
     * 
     * @type {string}
     * @memberof PreguntaNueva
     */
    enunciado: string;
    /**
     * 
     * @type {string}
     * @memberof PreguntaNueva
     */
    codigo?: string;
    /**
     * 
     * @type {string}
     * @memberof PreguntaNueva
     */
    estado: string;
    /**
     * 
     * @type {Array<Respuesta>}
     * @memberof PreguntaNueva
     */
    respuestas: Array<Respuesta>;
    /**
     * 
     * @type {Array<Categoria>}
     * @memberof PreguntaNueva
     */
    categorias: Array<Categoria>;
}

/**
 * Check if a given object implements the PreguntaNueva interface.
 */
export function instanceOfPreguntaNueva(value: object): value is PreguntaNueva {
    if (!('enunciado' in value) || value['enunciado'] === undefined) return false;
    if (!('estado' in value) || value['estado'] === undefined) return false;
    if (!('respuestas' in value) || value['respuestas'] === undefined) return false;
    if (!('categorias' in value) || value['categorias'] === undefined) return false;
    return true;
}

export function PreguntaNuevaFromJSON(json: any): PreguntaNueva {
    return PreguntaNuevaFromJSONTyped(json, false);
}

export function PreguntaNuevaFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreguntaNueva {
    if (json == null) {
        return json;
    }
    return {
        
        'enunciado': json['enunciado'],
        'codigo': json['codigo'] == null ? undefined : json['codigo'],
        'estado': json['estado'],
        'respuestas': ((json['respuestas'] as Array<any>).map(RespuestaFromJSON)),
        'categorias': ((json['categorias'] as Array<any>).map(CategoriaFromJSON)),
    };
}

export function PreguntaNuevaToJSON(json: any): PreguntaNueva {
    return PreguntaNuevaToJSONTyped(json, false);
}

export function PreguntaNuevaToJSONTyped(value?: PreguntaNueva | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enunciado': value['enunciado'],
        'codigo': value['codigo'],
        'estado': value['estado'],
        'respuestas': ((value['respuestas'] as Array<any>).map(RespuestaToJSON)),
        'categorias': ((value['categorias'] as Array<any>).map(CategoriaToJSON)),
    };
}

