/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PreguntaUpdate
 */
export interface PreguntaUpdate {
    /**
     * 
     * @type {string}
     * @memberof PreguntaUpdate
     */
    enunciado: string;
}

/**
 * Check if a given object implements the PreguntaUpdate interface.
 */
export function instanceOfPreguntaUpdate(value: object): value is PreguntaUpdate {
    if (!('enunciado' in value) || value['enunciado'] === undefined) return false;
    return true;
}

export function PreguntaUpdateFromJSON(json: any): PreguntaUpdate {
    return PreguntaUpdateFromJSONTyped(json, false);
}

export function PreguntaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PreguntaUpdate {
    if (json == null) {
        return json;
    }
    return {
        
        'enunciado': json['enunciado'],
    };
}

export function PreguntaUpdateToJSON(json: any): PreguntaUpdate {
    return PreguntaUpdateToJSONTyped(json, false);
}

export function PreguntaUpdateToJSONTyped(value?: PreguntaUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enunciado': value['enunciado'],
    };
}

