/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Categoria } from './Categoria';
import {
    CategoriaFromJSON,
    CategoriaFromJSONTyped,
    CategoriaToJSON,
    CategoriaToJSONTyped,
} from './Categoria';
import type { Respuesta } from './Respuesta';
import {
    RespuestaFromJSON,
    RespuestaFromJSONTyped,
    RespuestaToJSON,
    RespuestaToJSONTyped,
} from './Respuesta';

/**
 * 
 * @export
 * @interface Pregunta
 */
export interface Pregunta {
    /**
     * 
     * @type {string}
     * @memberof Pregunta
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Pregunta
     */
    enunciado: string;
    /**
     * 
     * @type {Array<Respuesta>}
     * @memberof Pregunta
     */
    respuestas: Array<Respuesta>;
    /**
     * 
     * @type {Array<Categoria>}
     * @memberof Pregunta
     */
    categorias?: Array<Categoria>;
}

/**
 * Check if a given object implements the Pregunta interface.
 */
export function instanceOfPregunta(value: object): value is Pregunta {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('enunciado' in value) || value['enunciado'] === undefined) return false;
    if (!('respuestas' in value) || value['respuestas'] === undefined) return false;
    return true;
}

export function PreguntaFromJSON(json: any): Pregunta {
    return PreguntaFromJSONTyped(json, false);
}

export function PreguntaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Pregunta {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'enunciado': json['enunciado'],
        'respuestas': ((json['respuestas'] as Array<any>).map(RespuestaFromJSON)),
        'categorias': json['categorias'] == null ? undefined : ((json['categorias'] as Array<any>).map(CategoriaFromJSON)),
    };
}

export function PreguntaToJSON(json: any): Pregunta {
    return PreguntaToJSONTyped(json, false);
}

export function PreguntaToJSONTyped(value?: Pregunta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'enunciado': value['enunciado'],
        'respuestas': ((value['respuestas'] as Array<any>).map(RespuestaToJSON)),
        'categorias': value['categorias'] == null ? undefined : ((value['categorias'] as Array<any>).map(CategoriaToJSON)),
    };
}

