/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegistrarIntentoPreguntaRequest
 */
export interface RegistrarIntentoPreguntaRequest {
    /**
     * Indica si la respuesta fue correcta
     * @type {boolean}
     * @memberof RegistrarIntentoPreguntaRequest
     */
    acertada: boolean;
}

/**
 * Check if a given object implements the RegistrarIntentoPreguntaRequest interface.
 */
export function instanceOfRegistrarIntentoPreguntaRequest(value: object): value is RegistrarIntentoPreguntaRequest {
    if (!('acertada' in value) || value['acertada'] === undefined) return false;
    return true;
}

export function RegistrarIntentoPreguntaRequestFromJSON(json: any): RegistrarIntentoPreguntaRequest {
    return RegistrarIntentoPreguntaRequestFromJSONTyped(json, false);
}

export function RegistrarIntentoPreguntaRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegistrarIntentoPreguntaRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'acertada': json['acertada'],
    };
}

export function RegistrarIntentoPreguntaRequestToJSON(json: any): RegistrarIntentoPreguntaRequest {
    return RegistrarIntentoPreguntaRequestToJSONTyped(json, false);
}

export function RegistrarIntentoPreguntaRequestToJSONTyped(value?: RegistrarIntentoPreguntaRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'acertada': value['acertada'],
    };
}

