/* tslint:disable */
/* eslint-disable */
/**
 * PreparaTAI API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Respuesta
 */
export interface Respuesta {
    /**
     * 
     * @type {string}
     * @memberof Respuesta
     */
    enunciado: string;
    /**
     * 
     * @type {boolean}
     * @memberof Respuesta
     */
    correcta: boolean;
}

/**
 * Check if a given object implements the Respuesta interface.
 */
export function instanceOfRespuesta(value: object): value is Respuesta {
    if (!('enunciado' in value) || value['enunciado'] === undefined) return false;
    if (!('correcta' in value) || value['correcta'] === undefined) return false;
    return true;
}

export function RespuestaFromJSON(json: any): Respuesta {
    return RespuestaFromJSONTyped(json, false);
}

export function RespuestaFromJSONTyped(json: any, ignoreDiscriminator: boolean): Respuesta {
    if (json == null) {
        return json;
    }
    return {
        
        'enunciado': json['enunciado'],
        'correcta': json['correcta'],
    };
}

export function RespuestaToJSON(json: any): Respuesta {
    return RespuestaToJSONTyped(json, false);
}

export function RespuestaToJSONTyped(value?: Respuesta | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enunciado': value['enunciado'],
        'correcta': value['correcta'],
    };
}

