/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/pregunta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener preguntas */
        get: operations["getAllPreguntas"];
        put?: never;
        /** Guardar una pregunta */
        post: operations["createPregunta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        /** Obtener una pregunta por id */
        get: operations["getOnePreguntasById"];
        put?: never;
        post?: never;
        /** Eliminar una pregunta por id */
        delete: operations["deletePreguntaById"];
        options?: never;
        head?: never;
        /** Actualizar una pregunta por id */
        patch: operations["updatePreguntaById"];
        trace?: never;
    };
    "/pregunta/{id}/intentos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registrar intento de respuesta a una pregunta */
        post: operations["registrarIntentoPregunta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/{id}/enterrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Entierra la pregunta para que no salga */
        post: operations["enterrarPregunta"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/todas/desenterrar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Desentierrar todas las preguntas de la base de datos */
        get: operations["desenterrarTodasLasPreguntas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/getNumeroDePreguntas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener el numero de preguntas actuales en la base de datos */
        get: operations["getNumeroDePreguntas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/porCategoria/{id}": {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Número de preguntas por página */
                limit?: number;
                /** @description Semilla para randomizar las preguntas */
                seed?: number;
            };
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        /** Obtener las preguntas que pertenecen a una categoria dada */
        get: operations["getPreguntasPorCategoria"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pregunta/estadisticas/reiniciar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reincia las estadisticas de las preguntas */
        get: operations["reiniciarContadorDeEstadisticas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categoria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener categorias */
        get: operations["getAllCategorias"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categoria/resumen": {
        parameters: {
            query?: {
                /** @description Tipo de Cateogiras que queremos (Cuestionarios / No Cuestionarios) */
                tipo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener categorias con número de preguntas */
        get: operations["getCategoriasResumen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categoria/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la categoria */
                id: string;
            };
            cookie?: never;
        };
        /** Obtener una categoria por id */
        get: operations["getOneCategoriaById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/gruposDePreguntasRelacionadas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Grupos de Preguntas GrupoPreguntasRelacionadas */
        get: operations["getAllGruposDePreguntasRelacionadas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/examenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener un listado de los Examenes */
        get: operations["getAllExamenes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Categoria: {
            id: string;
            nombre: string;
            tipo: string;
        };
        CategoriaResumen: {
            /** @example 0000-00000-0000000-0000 */
            id: string;
            /** @example Java */
            nombre: string;
            /** @example 35 */
            numeroPreguntas: number;
        };
        Respuesta: {
            enunciado: string;
            correcta: boolean;
        };
        Estadistica: {
            aciertos: number;
            fallos: number;
            total: number;
        };
        Pregunta: {
            id: string;
            enunciado: string;
            estado: string;
            descartada: boolean;
            respuestas: components["schemas"]["Respuesta"][];
            categorias?: components["schemas"]["Categoria"][];
            estadisticas: components["schemas"]["Estadistica"];
        };
        PreguntaUpdate: {
            enunciado: string;
        };
        GrupoPreguntasRelacionadas: {
            id: string;
            textoBase: string;
            preguntas: components["schemas"]["Pregunta"][];
        };
        Examen: {
            id: string;
            nombre: string;
            anio?: number;
            grupo?: string;
            subgrupo?: string;
            preguntas?: (components["schemas"]["Pregunta"] | components["schemas"]["GrupoPreguntasRelacionadas"])[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAllPreguntas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de preguntas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"][];
                };
            };
        };
    };
    createPregunta: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Pregunta"];
            };
        };
        responses: {
            /** @description Pregunta guardada con exito */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"][];
                };
            };
        };
    };
    getOnePreguntasById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pregunta por ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"];
                };
            };
        };
    };
    deletePreguntaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pregunta eliminada por ID */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePreguntaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreguntaUpdate"];
            };
        };
        responses: {
            /** @description Pregunta actualizada por ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"];
                };
            };
        };
    };
    registrarIntentoPregunta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Indica si la respuesta fue correcta */
                    acertada: boolean;
                };
            };
        };
        responses: {
            /** @description Intento registrado correctamente, sin contenido de respuesta */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enterrarPregunta: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Intento registrado correctamente, sin contenido de respuesta */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    desenterrarTodasLasPreguntas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas las preguntas fueron desenterradas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getNumeroDePreguntas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Numero de preguntas en la abse de datos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number;
                };
            };
        };
    };
    getPreguntasPorCategoria: {
        parameters: {
            query?: {
                /** @description Número de página (empieza en 1) */
                page?: number;
                /** @description Número de preguntas por página */
                limit?: number;
                /** @description Semilla para randomizar las preguntas */
                seed?: number;
            };
            header?: never;
            path: {
                /** @description el identificador de la pregunta */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pregunta que pertenecen a una categoria */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pregunta"][];
                };
            };
        };
    };
    reiniciarContadorDeEstadisticas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estadisticas reiniciadas */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getAllCategorias: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorias */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"][];
                };
            };
        };
    };
    getCategoriasResumen: {
        parameters: {
            query?: {
                /** @description Tipo de Cateogiras que queremos (Cuestionarios / No Cuestionarios) */
                tipo?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de categorias con número de preguntas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoriaResumen"][];
                };
            };
        };
    };
    getOneCategoriaById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description el identificador de la categoria */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categoria por ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Categoria"];
                };
            };
        };
    };
    getAllGruposDePreguntasRelacionadas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de preguntas GrupoPreguntasRelacionadas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrupoPreguntasRelacionadas"][];
                };
            };
        };
    };
    getAllExamenes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de Examenes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Examen"][];
                };
            };
        };
    };
}
